### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by eemeli** [comment]
Is there a real-world use case that would benefit from this?

**Comment by bluelovers** [comment]
yes, because some ide can't support if u put endpoint file in sub dir

if u put ur file in root dir, this is didn't need

it make i have use this code for avoid it
```
import { parse, Tree, stringify, StringifyOptions, Line, parseLines } from 'dot-properties/lib';
```

**Comment by eemeli** [comment]
That's rather surprising. Which IDE is this, if I may ask?

I do hope that defining both `types` and `typings` is more than what's actually required. If you could drop one of them from the PR, I'll be happy to merge it.

**Comment by bluelovers** [comment]
webstorm and all jetbrains ide

**Comment by bluelovers** [comment]
github mobile is so hard edit lol

**Pull request merged**
